//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 01:28:14 PM EDT 
//


package gatech.team13.classproject.jxab;




/**
 * <p>Java class for actType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="actType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="templateId" type="{urn:hl7-org:v3}templateIdType"/>
 *         &lt;element name="id" type="{urn:hl7-org:v3}idType"/>
 *         &lt;element name="code" type="{urn:hl7-org:v3}codeType"/>
 *         &lt;element name="statusCode" type="{urn:hl7-org:v3}statusCodeType"/>
 *         &lt;element name="effectiveTime" type="{urn:hl7-org:v3}effectiveTimeType"/>
 *         &lt;element name="entryRelationship" type="{urn:hl7-org:v3}entryRelationshipType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="classCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="moodCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class ActTypeDF {

    protected TemplateIdType templateId;
    protected IdType id;
    protected CodeTypeDF code;
    protected StatusCodeType statusCode;
    protected EffectiveTimeTypeDF effectiveTime;
    protected EntryRelationshipTypeDF entryRelationship;
    protected String classCode;
    protected String moodCode;

    public ActTypeDF(ActType a) {
    	this.templateId = a.getTemplateId();
    	this.id = a.getId();
    	if(a.getCode() != null) {
    		this.code = new CodeTypeDF(a.getCode());
    	}
    	this.statusCode = a.getStatusCode();
    	if(a.getEffectiveTime() != null) {
    		this.effectiveTime = new EffectiveTimeTypeDF(a.getEffectiveTime());
    	}
    	if(a.getEntryRelationship() != null) {
    		this.entryRelationship = new EntryRelationshipTypeDF(a.getEntryRelationship());
    	}
    	this.classCode = a.getClassCode();
    	this.moodCode = a.getMoodCode();
    }
    /**
     * Gets the value of the templateId property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateIdType }
     *     
     */
    public TemplateIdType getTemplateId() {
        return templateId;
    }

    /**
     * Sets the value of the templateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateIdType }
     *     
     */
    public void setTemplateId(TemplateIdType value) {
        this.templateId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setId(IdType value) {
        this.id = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeTypeDF getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setCode(CodeTypeDF value) {
        this.code = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCodeType }
     *     
     */
    public StatusCodeType getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCodeType }
     *     
     */
    public void setStatusCode(StatusCodeType value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the effectiveTime property.
     * 
     * @return
     *     possible object is
     *     {@link EffectiveTimeType }
     *     
     */
    public EffectiveTimeTypeDF getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * Sets the value of the effectiveTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EffectiveTimeType }
     *     
     */
    public void setEffectiveTime(EffectiveTimeTypeDF value) {
        this.effectiveTime = value;
    }

    /**
     * Gets the value of the entryRelationship property.
     * 
     * @return
     *     possible object is
     *     {@link EntryRelationshipType }
     *     
     */
    public EntryRelationshipTypeDF getEntryRelationship() {
        return entryRelationship;
    }

    /**
     * Sets the value of the entryRelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryRelationshipType }
     *     
     */
    public void setEntryRelationship(EntryRelationshipTypeDF value) {
        this.entryRelationship = value;
    }

    /**
     * Gets the value of the classCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * Sets the value of the classCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassCode(String value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the moodCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoodCode() {
        return moodCode;
    }

    /**
     * Sets the value of the moodCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoodCode(String value) {
        this.moodCode = value;
    }

}
