//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 01:28:14 PM EDT 
//


package gatech.team13.classproject.jxab;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="encounter" type="{urn:hl7-org:v3}encounterType" minOccurs="0"/>
 *         &lt;element name="substanceAdministration" type="{urn:hl7-org:v3}substanceAdministrationType" minOccurs="0"/>
 *         &lt;element name="act" type="{urn:hl7-org:v3}actType" minOccurs="0"/>
 *         &lt;element name="organizer" type="{urn:hl7-org:v3}organizerType" minOccurs="0"/>
 *         &lt;element name="observation" type="{urn:hl7-org:v3}observationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="typeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entryType", propOrder = {
    "encounter",
    "substanceAdministration",
    "act",
    "organizer",
    "observation"
})
public class EntryType {

    protected EncounterType encounter;
    protected SubstanceAdministrationType substanceAdministration;
    protected ActType act;
    protected OrganizerType organizer;
    protected ObservationType observation;
    @XmlAttribute(name = "typeCode")
    protected String typeCode;

    /**
     * Gets the value of the encounter property.
     * 
     * @return
     *     possible object is
     *     {@link EncounterType }
     *     
     */
    public EncounterType getEncounter() {
        return encounter;
    }

    /**
     * Sets the value of the encounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncounterType }
     *     
     */
    public void setEncounter(EncounterType value) {
        this.encounter = value;
    }

    /**
     * Gets the value of the substanceAdministration property.
     * 
     * @return
     *     possible object is
     *     {@link SubstanceAdministrationType }
     *     
     */
    public SubstanceAdministrationType getSubstanceAdministration() {
        return substanceAdministration;
    }

    /**
     * Sets the value of the substanceAdministration property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubstanceAdministrationType }
     *     
     */
    public void setSubstanceAdministration(SubstanceAdministrationType value) {
        this.substanceAdministration = value;
    }

    /**
     * Gets the value of the act property.
     * 
     * @return
     *     possible object is
     *     {@link ActType }
     *     
     */
    public ActType getAct() {
        return act;
    }

    /**
     * Sets the value of the act property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActType }
     *     
     */
    public void setAct(ActType value) {
        this.act = value;
    }

    /**
     * Gets the value of the organizer property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizerType }
     *     
     */
    public OrganizerType getOrganizer() {
        return organizer;
    }

    /**
     * Sets the value of the organizer property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizerType }
     *     
     */
    public void setOrganizer(OrganizerType value) {
        this.organizer = value;
    }

    /**
     * Gets the value of the observation property.
     * 
     * @return
     *     possible object is
     *     {@link ObservationType }
     *     
     */
    public ObservationType getObservation() {
        return observation;
    }

    /**
     * Sets the value of the observation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservationType }
     *     
     */
    public void setObservation(ObservationType value) {
        this.observation = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeCode(String value) {
        this.typeCode = value;
    }

}
