//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 01:28:14 PM EDT 
//


package gatech.team13.classproject.jxab;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gatech.team13.classproject.jxab package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClinicalDocument_QNAME = new QName("urn:hl7-org:v3", "ClinicalDocument");
    private final static QName _CodeTypeOriginalText_QNAME = new QName("urn:hl7-org:v3", "originalText");
    private final static QName _EffectiveTimeTypeHigh_QNAME = new QName("urn:hl7-org:v3", "high");
    private final static QName _EffectiveTimeTypeLow_QNAME = new QName("urn:hl7-org:v3", "low");
    private final static QName _TdTypeContent_QNAME = new QName("urn:hl7-org:v3", "content");
    private final static QName _SectionTypeTextTable_QNAME = new QName("urn:hl7-org:v3", "table");
    private final static QName _SectionTypeTextList_QNAME = new QName("urn:hl7-org:v3", "list");
    private final static QName _SectionTypeTextReference_QNAME = new QName("urn:hl7-org:v3", "reference");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gatech.team13.classproject.jxab
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SectionType }
     * 
     */
    public SectionType createSectionType() {
        return new SectionType();
    }

    /**
     * Create an instance of {@link ClinicalDocumentType }
     * 
     */
    public ClinicalDocumentType createClinicalDocumentType() {
        return new ClinicalDocumentType();
    }

    /**
     * Create an instance of {@link RouteCodeType }
     * 
     */
    public RouteCodeType createRouteCodeType() {
        return new RouteCodeType();
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType() {
        return new TimeType();
    }

    /**
     * Create an instance of {@link ActType }
     * 
     */
    public ActType createActType() {
        return new ActType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link EncounterType }
     * 
     */
    public EncounterType createEncounterType() {
        return new EncounterType();
    }

    /**
     * Create an instance of {@link AssignedAuthorType }
     * 
     */
    public AssignedAuthorType createAssignedAuthorType() {
        return new AssignedAuthorType();
    }

    /**
     * Create an instance of {@link RepresentedCustodianOrganizationType }
     * 
     */
    public RepresentedCustodianOrganizationType createRepresentedCustodianOrganizationType() {
        return new RepresentedCustodianOrganizationType();
    }

    /**
     * Create an instance of {@link ManufacturedProductType }
     * 
     */
    public ManufacturedProductType createManufacturedProductType() {
        return new ManufacturedProductType();
    }

    /**
     * Create an instance of {@link TheadType }
     * 
     */
    public TheadType createTheadType() {
        return new TheadType();
    }

    /**
     * Create an instance of {@link AdministrativeGenderCodeType }
     * 
     */
    public AdministrativeGenderCodeType createAdministrativeGenderCodeType() {
        return new AdministrativeGenderCodeType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link LanguageCodeType }
     * 
     */
    public LanguageCodeType createLanguageCodeType() {
        return new LanguageCodeType();
    }

    /**
     * Create an instance of {@link ObservationType }
     * 
     */
    public ObservationType createObservationType() {
        return new ObservationType();
    }

    /**
     * Create an instance of {@link ComponentType }
     * 
     */
    public ComponentType createComponentType() {
        return new ComponentType();
    }

    /**
     * Create an instance of {@link StatusCodeType }
     * 
     */
    public StatusCodeType createStatusCodeType() {
        return new StatusCodeType();
    }

    /**
     * Create an instance of {@link OrganizerType }
     * 
     */
    public OrganizerType createOrganizerType() {
        return new OrganizerType();
    }

    /**
     * Create an instance of {@link TypeIdType }
     * 
     */
    public TypeIdType createTypeIdType() {
        return new TypeIdType();
    }

    /**
     * Create an instance of {@link ManufacturedMaterialType }
     * 
     */
    public ManufacturedMaterialType createManufacturedMaterialType() {
        return new ManufacturedMaterialType();
    }

    /**
     * Create an instance of {@link AssignedCustodianType }
     * 
     */
    public AssignedCustodianType createAssignedCustodianType() {
        return new AssignedCustodianType();
    }

    /**
     * Create an instance of {@link TableType }
     * 
     */
    public TableType createTableType() {
        return new TableType();
    }

    /**
     * Create an instance of {@link CustodianType }
     * 
     */
    public CustodianType createCustodianType() {
        return new CustodianType();
    }

    /**
     * Create an instance of {@link RecordTargetType }
     * 
     */
    public RecordTargetType createRecordTargetType() {
        return new RecordTargetType();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientType();
    }

    /**
     * Create an instance of {@link EntryRelationshipType }
     * 
     */
    public EntryRelationshipType createEntryRelationshipType() {
        return new EntryRelationshipType();
    }

    /**
     * Create an instance of {@link ConfidentialityCodeType }
     * 
     */
    public ConfidentialityCodeType createConfidentialityCodeType() {
        return new ConfidentialityCodeType();
    }

    /**
     * Create an instance of {@link IdType }
     * 
     */
    public IdType createIdType() {
        return new IdType();
    }

    /**
     * Create an instance of {@link TrType }
     * 
     */
    public TrType createTrType() {
        return new TrType();
    }

    /**
     * Create an instance of {@link OriginalTextType }
     * 
     */
    public OriginalTextType createOriginalTextType() {
        return new OriginalTextType();
    }

    /**
     * Create an instance of {@link TdType }
     * 
     */
    public TdType createTdType() {
        return new TdType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link TelecomType }
     * 
     */
    public TelecomType createTelecomType() {
        return new TelecomType();
    }

    /**
     * Create an instance of {@link DoseQuantityType }
     * 
     */
    public DoseQuantityType createDoseQuantityType() {
        return new DoseQuantityType();
    }

    /**
     * Create an instance of {@link SubstanceAdministrationType }
     * 
     */
    public SubstanceAdministrationType createSubstanceAdministrationType() {
        return new SubstanceAdministrationType();
    }

    /**
     * Create an instance of {@link AuthorType }
     * 
     */
    public AuthorType createAuthorType() {
        return new AuthorType();
    }

    /**
     * Create an instance of {@link HighType }
     * 
     */
    public HighType createHighType() {
        return new HighType();
    }

    /**
     * Create an instance of {@link EffectiveTimeType }
     * 
     */
    public EffectiveTimeType createEffectiveTimeType() {
        return new EffectiveTimeType();
    }

    /**
     * Create an instance of {@link AssignedPersonType }
     * 
     */
    public AssignedPersonType createAssignedPersonType() {
        return new AssignedPersonType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link ListType }
     * 
     */
    public ListType createListType() {
        return new ListType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link PatientRoleType }
     * 
     */
    public PatientRoleType createPatientRoleType() {
        return new PatientRoleType();
    }

    /**
     * Create an instance of {@link RealmCodeType }
     * 
     */
    public RealmCodeType createRealmCodeType() {
        return new RealmCodeType();
    }

    /**
     * Create an instance of {@link AddrType }
     * 
     */
    public AddrType createAddrType() {
        return new AddrType();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link TemplateIdType }
     * 
     */
    public TemplateIdType createTemplateIdType() {
        return new TemplateIdType();
    }

    /**
     * Create an instance of {@link BirthTimeType }
     * 
     */
    public BirthTimeType createBirthTimeType() {
        return new BirthTimeType();
    }

    /**
     * Create an instance of {@link AdministrationUnitCodeType }
     * 
     */
    public AdministrationUnitCodeType createAdministrationUnitCodeType() {
        return new AdministrationUnitCodeType();
    }

    /**
     * Create an instance of {@link ConsumableType }
     * 
     */
    public ConsumableType createConsumableType() {
        return new ConsumableType();
    }

    /**
     * Create an instance of {@link TbodyType }
     * 
     */
    public TbodyType createTbodyType() {
        return new TbodyType();
    }

    /**
     * Create an instance of {@link LowType }
     * 
     */
    public LowType createLowType() {
        return new LowType();
    }

    /**
     * Create an instance of {@link StructuredBodyType }
     * 
     */
    public StructuredBodyType createStructuredBodyType() {
        return new StructuredBodyType();
    }

    /**
     * Create an instance of {@link SectionType.Text }
     * 
     */
    public SectionType.Text createSectionTypeText() {
        return new SectionType.Text();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClinicalDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "ClinicalDocument")
    public JAXBElement<ClinicalDocumentType> createClinicalDocument(ClinicalDocumentType value) {
        return new JAXBElement<ClinicalDocumentType>(_ClinicalDocument_QNAME, ClinicalDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OriginalTextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "originalText", scope = CodeType.class)
    public JAXBElement<OriginalTextType> createCodeTypeOriginalText(OriginalTextType value) {
        return new JAXBElement<OriginalTextType>(_CodeTypeOriginalText_QNAME, OriginalTextType.class, CodeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HighType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "high", scope = EffectiveTimeType.class)
    public JAXBElement<HighType> createEffectiveTimeTypeHigh(HighType value) {
        return new JAXBElement<HighType>(_EffectiveTimeTypeHigh_QNAME, HighType.class, EffectiveTimeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LowType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "low", scope = EffectiveTimeType.class)
    public JAXBElement<LowType> createEffectiveTimeTypeLow(LowType value) {
        return new JAXBElement<LowType>(_EffectiveTimeTypeLow_QNAME, LowType.class, EffectiveTimeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = TdType.class)
    public JAXBElement<ContentType> createTdTypeContent(ContentType value) {
        return new JAXBElement<ContentType>(_TdTypeContent_QNAME, ContentType.class, TdType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "table", scope = SectionType.Text.class)
    public JAXBElement<TableType> createSectionTypeTextTable(TableType value) {
        return new JAXBElement<TableType>(_SectionTypeTextTable_QNAME, TableType.class, SectionType.Text.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "list", scope = SectionType.Text.class)
    public JAXBElement<ListType> createSectionTypeTextList(ListType value) {
        return new JAXBElement<ListType>(_SectionTypeTextList_QNAME, ListType.class, SectionType.Text.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "reference", scope = SectionType.Text.class)
    public JAXBElement<ReferenceType> createSectionTypeTextReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_SectionTypeTextReference_QNAME, ReferenceType.class, SectionType.Text.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = SectionType.Text.class)
    public JAXBElement<ContentType> createSectionTypeTextContent(ContentType value) {
        return new JAXBElement<ContentType>(_TdTypeContent_QNAME, ContentType.class, SectionType.Text.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "table", scope = TextType.class)
    public JAXBElement<TableType> createTextTypeTable(TableType value) {
        return new JAXBElement<TableType>(_SectionTypeTextTable_QNAME, TableType.class, TextType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "list", scope = TextType.class)
    public JAXBElement<ListType> createTextTypeList(ListType value) {
        return new JAXBElement<ListType>(_SectionTypeTextList_QNAME, ListType.class, TextType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "reference", scope = TextType.class)
    public JAXBElement<ReferenceType> createTextTypeReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_SectionTypeTextReference_QNAME, ReferenceType.class, TextType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "content", scope = TextType.class)
    public JAXBElement<ContentType> createTextTypeContent(ContentType value) {
        return new JAXBElement<ContentType>(_TdTypeContent_QNAME, ContentType.class, TextType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:hl7-org:v3", name = "reference", scope = OriginalTextType.class)
    public JAXBElement<ReferenceType> createOriginalTextTypeReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_SectionTypeTextReference_QNAME, ReferenceType.class, OriginalTextType.class, value);
    }

}
