//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 01:28:14 PM EDT 
//


package gatech.team13.classproject.jxab;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recordTargetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recordTargetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="patientRole" type="{urn:hl7-org:v3}patientRoleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recordTargetType", propOrder = {
    "patientRole"
})
public class RecordTargetType {

    @XmlElement(required = true)
    protected PatientRoleType patientRole;

    /**
     * Gets the value of the patientRole property.
     * 
     * @return
     *     possible object is
     *     {@link PatientRoleType }
     *     
     */
    public PatientRoleType getPatientRole() {
        return patientRole;
    }

    /**
     * Sets the value of the patientRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientRoleType }
     *     
     */
    public void setPatientRole(PatientRoleType value) {
        this.patientRole = value;
    }

}
