//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 01:28:14 PM EDT 
//


package gatech.team13.classproject.jxab;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="thead" type="{urn:hl7-org:v3}theadType"/>
 *         &lt;element name="tbody" type="{urn:hl7-org:v3}tbodyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="border" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tableType", propOrder = {
    "thead",
    "tbody"
})
public class TableTypeDF {

    @XmlElement(required = true)
    protected TheadType thead;
    @XmlElement(required = true)
    protected TbodyTypeDF tbody;
    @XmlAttribute(name = "border")
    protected Byte border;
    @XmlAttribute(name = "width")
    protected String width;

    public TableTypeDF(TableType t) {
    	this.thead = t.getThead();
    	if(t.getTbody() != null) {
    		this.tbody = new TbodyTypeDF(t.getTbody());
    	}
    	this.border = t.getBorder();
    	this.width = t.getWidth();
    }
    /**
     * Gets the value of the thead property.
     * 
     * @return
     *     possible object is
     *     {@link TheadType }
     *     
     */
    public TheadType getThead() {
        return thead;
    }

    /**
     * Sets the value of the thead property.
     * 
     * @param value
     *     allowed object is
     *     {@link TheadType }
     *     
     */
    public void setThead(TheadType value) {
        this.thead = value;
    }

    /**
     * Gets the value of the tbody property.
     * 
     * @return
     *     possible object is
     *     {@link TbodyType }
     *     
     */
    public TbodyTypeDF getTbody() {
        return tbody;
    }

    /**
     * Sets the value of the tbody property.
     * 
     * @param value
     *     allowed object is
     *     {@link TbodyType }
     *     
     */
    public void setTbody(TbodyTypeDF value) {
        this.tbody = value;
    }

    /**
     * Gets the value of the border property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getBorder() {
        return border;
    }

    /**
     * Sets the value of the border property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setBorder(Byte value) {
        this.border = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

}
