//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.04 at 01:28:14 PM EDT 
//


package gatech.team13.classproject.jxab;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;




/**
 * <p>Java class for textType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="textType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="table" type="{urn:hl7-org:v3}tableType" minOccurs="0"/>
 *         &lt;element name="reference" type="{urn:hl7-org:v3}referenceType" minOccurs="0"/>
 *         &lt;element name="content" type="{urn:hl7-org:v3}contentType" minOccurs="0"/>
 *         &lt;element name="list" type="{urn:hl7-org:v3}listType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class TextTypeDF {

    protected List<Object> content;

    public TextTypeDF(TextType t) {
    	content = new ArrayList<Object>();
    	for(Serializable s : t.getContent()) {
    		if(s.getClass().equals(javax.xml.bind.JAXBElement.class)) {
    			try {
    				javax.xml.bind.JAXBElement tmp = (javax.xml.bind.JAXBElement) s;
    				if(tmp.getDeclaredType().equals(TableType.class)) {
    					content.add(new TableTypeDF((TableType)tmp.getValue()));
    				}else if(tmp.getDeclaredType().equals(ReferenceType.class)) {
    					content.add((ReferenceType)tmp.getValue());
    				}else if(tmp.getDeclaredType().equals(ContentType.class)) {
    					content.add((ContentType)tmp.getValue());
    				}else if(tmp.getDeclaredType().equals(ListType.class)) {
    					content.add((ListType)tmp.getValue());
    				}else {
    					//(ReferenceType)
    					content.add(tmp.getValue());
    				}
    			}catch(ClassCastException e) {
    				System.out.println("Class Cast Expection TextTypeDF");
    			}
    		}else {
    			content.add(s);
    		}
    	}
//    	content = new ArrayList<Serializable>();
//    	for(Serializable s : t.getContent()) {
//    		if(s.getClass().equals(javax.xml.bind.JAXBElement.class)) {
//    			try {
//    				content.add((ReferenceType)s);
//    			}catch(ClassCastException e) {
//    				
//    			}
//    		}else {
//    			content.add(s);
//    		}
//    	}
    }
    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ContentType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListType }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TableType }{@code >}
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
